using System;
using Authentication.Domain;

namespace Authentication.Account.Models
{
  public enum TokenKind
  {
    MultiFactorAuth = 0,
    PasswordReset = 1,
    EmailVerification = 2
  }

  public class AccountToken : DomainEntity<Guid>
  {
    public AccountToken()
    {
      
    }

    public delegate AccountToken Factory();

    public virtual TokenKind Kind { get; set; }

    //Generated by the Db on insert
    public virtual DateTime DateCreated { get; set; }

    public virtual DateTime ExpirationDate { get; set; }

    public virtual string Value { get; set; }

    public virtual bool IsExpired => ExpirationDate < DateTime.UtcNow;
  }
}
